### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by kennyendowed** [bitfumes/laravel-angular-authentication#10]
Hello thanks for this wonderful tutorial pls i need an assist i want to save user login details like user id , username or email etc .for me to be able to use it anywhere in the project

**Comment by ajharulabedeen** [comment]
i think to as solution of your problem, you can use `auth()->user()` method, to get the current logger user. 
Current Logged User : 
`$currentLoggedMail = auth()->user()->email;`
```
public static function getUserId()
    {
        $currentLoggedMail = auth()->user()->email;
        try{
            $userID = User::select('id')->where('email', $currentLoggedMail)->get()[0]->id;
        }catch(Exception $e){
            error_log("Error In Getting user ID of the current Logged user.");
        }
        return $userID;
    }

```
    public static function getLoggerEmailId(): string
    {
        $currentLoggedMail = auth()->user()->email;
    }

**Comment by kennyendowed** [comment]
Ok thanks for this info but this not what am asking for . i know how to get user info from db with laravel it how to pass it in angular i want to know .how to store user information in angular and pass it to other view components

**Comment by ajharulabedeen** [comment]
There are several ways to do so. It depends on your requirement. so far i think, 
one of them : You can create to communicate with each other, observer and subscriber. 
These following links can help you:
[https://stackoverflow.com/questions/30501577/how-to-communicate-between-component-in-angular](url)
[https://medium.com/@mirokoczka/3-ways-to-communicate-between-angular-components-a1e3f3304ecb](url)

You can also check my current working repository in GitHub. where i have shared JWT token, with other components. And Feel free to ask me about the project. 
`user = new BehaviorSubject<User>(null);`
By using BehaviorSubject u can do so. 
https://github.com/ajharulabedeen/alumni/tree/dev/fontend/src/app/auth

**Comment by kennyendowed** [comment]
Aii thanks i go through it and get back to you thanks for your time
